#!/usr/bin/env python3
"""Generate INDEX.md files for each content directory in the Gaia Minds repository.

Scans content directories, extracts metadata from markdown files, and produces
up-to-date INDEX.md files listing every document with its title, description,
and date.

Usage:
    python3 tools/generate-indexes.py            # regenerate all INDEX.md files
    python3 tools/generate-indexes.py --check     # exit 1 if any index is stale
    python3 tools/generate-indexes.py --dry-run   # print output without writing
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import NamedTuple

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Repository root is one level above `tools/`
REPO_ROOT = Path(__file__).resolve().parent.parent

# Content directories to index.  Each entry maps a directory name to a short
# human-readable description used as a subtitle in the generated INDEX.md.
CONTENT_DIRS: dict[str, str] = {
    "research": "Short, curated entry points for research content.",
    "resources": "Pointers to funding, compute, and sustainability resources.",
    "philosophy": "Core reflections that shape the project's values and intent.",
    "infrastructure": "Technical foundations and operational guidance.",
    "skills": "Entry points to agent skills and contribution guidance.",
}

# Files to skip when scanning directories.
SKIP_FILES = {"INDEX.md", "README.md", "RESOURCES.md"}

# Regex patterns
HEADING_RE = re.compile(r"^#\s+(.+)", re.MULTILINE)
DATE_FILENAME_RE = re.compile(r"^(\d{4}-\d{2})")
FRONTMATTER_DATE_RE = re.compile(r"^\*\*Date\*\*:\s*(\d{4}-\d{2}(?:-\d{2})?)", re.MULTILINE)
YAML_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
YAML_DATE_RE = re.compile(r"^date:\s*(\d{4}-\d{2}(?:-\d{2})?)", re.MULTILINE)

AUTO_GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED by tools/generate-indexes.py -- do not edit manually -->"
)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

class FileEntry(NamedTuple):
    """Metadata extracted from a single markdown file."""

    rel_path: str        # path relative to the content directory
    title: str           # first heading
    description: str     # first paragraph (truncated)
    date: str | None     # YYYY-MM or YYYY-MM-DD if available
    sort_key: tuple      # (date_desc, title_lower) for sorting


# ---------------------------------------------------------------------------
# Extraction helpers
# ---------------------------------------------------------------------------

def _extract_title(text: str) -> str:
    """Return the text of the first ``# heading`` in *text*."""
    match = HEADING_RE.search(text)
    if match:
        # Strip leading emoji + whitespace that some files use (e.g. architecture.md)
        title = match.group(1).strip()
        # Remove leading emoji characters (common unicode emoji ranges)
        title = re.sub(r"^[\U0001F300-\U0001FAFF\u2600-\u27BF\uFE0F]+\s*", "", title)
        return title.strip()
    return "Untitled"


def _extract_description(text: str) -> str:
    """Return the first non-empty paragraph after the title, truncated to ~150 chars."""
    # Skip YAML front-matter if present
    stripped = YAML_FRONTMATTER_RE.sub("", text).strip()

    lines = stripped.split("\n")
    # Find the title line, then look for the next paragraph
    found_title = False
    paragraph_lines: list[str] = []
    for line in lines:
        if not found_title:
            if HEADING_RE.match(line):
                found_title = True
            continue
        # Skip blank lines, horizontal rules, bold metadata lines
        sline = line.strip()
        if not sline:
            if paragraph_lines:
                break  # end of paragraph
            continue
        if sline.startswith("---"):
            if paragraph_lines:
                break
            continue
        if sline.startswith("**"):
            # Metadata lines like **Date**: ..., **Agent**: ...
            parts_bold = sline.split("**")
            if len(parts_bold) > 2 and ":" in parts_bold[2]:
                continue
        if sline.startswith("#"):
            # Hit next heading -- use it as description if we have nothing
            if not paragraph_lines:
                paragraph_lines.append(sline.lstrip("# ").strip())
            break
        paragraph_lines.append(sline)

    desc = " ".join(paragraph_lines).strip()
    if len(desc) > 150:
        # Truncate at the last word boundary before 150 chars
        desc = desc[:150].rsplit(" ", 1)[0].rstrip(".,;:") + "..."
    return desc


def _extract_date(filename: str, text: str) -> str | None:
    """Try to find a date from the filename or from in-file metadata."""
    stem = Path(filename).stem

    # 1. Filename like 2024-2025-safety-... or 2026-02-openclaw-...
    m = DATE_FILENAME_RE.match(stem)
    if m:
        return m.group(1)

    # 2. Bold metadata: **Date**: 2026-02-01
    m = FRONTMATTER_DATE_RE.search(text)
    if m:
        return m.group(1)

    # 3. YAML front-matter date field
    fm = YAML_FRONTMATTER_RE.match(text)
    if fm:
        m = YAML_DATE_RE.search(fm.group(1))
        if m:
            return m.group(1)

    return None


def _make_sort_key(date: str | None, title: str) -> tuple:
    """Return a sort key that orders newest-first, then alphabetically.

    We negate the date by subtracting each digit from 9 so that lexicographic
    ascending order gives newest dates first.  Entries without a date sort
    after all dated entries.  The title sorts A-Z (ascending).
    """
    if date:
        # Negate digits: "2026-02" -> "7973-97", so newer dates sort first ascending
        negated = "".join(
            str(9 - int(ch)) if ch.isdigit() else ch for ch in date
        )
    else:
        # No date -> sort after all dated entries
        negated = "9999-99"
    return (negated, title.lower())


# ---------------------------------------------------------------------------
# Scanning
# ---------------------------------------------------------------------------

def scan_directory(content_dir: Path) -> dict[str | None, list[FileEntry]]:
    """Scan *content_dir* and return entries grouped by subdirectory.

    The key ``None`` represents files directly in *content_dir* (no subdir).
    """
    groups: dict[str | None, list[FileEntry]] = {}

    for root, _dirs, files in os.walk(content_dir):
        root_path = Path(root)
        for fname in sorted(files):
            if not fname.endswith(".md"):
                continue
            # Skip known top-level docs and underscore-prefixed templates/helpers.
            if fname in SKIP_FILES or fname.startswith("_"):
                continue

            fpath = root_path / fname
            rel = fpath.relative_to(content_dir)

            # Determine subdirectory group (first component, or None)
            parts = rel.parts
            subdir: str | None = parts[0] if len(parts) > 1 else None

            text = fpath.read_text(encoding="utf-8", errors="replace")
            title = _extract_title(text)
            description = _extract_description(text)
            date = _extract_date(fname, text)
            sort_key = _make_sort_key(date, title)

            entry = FileEntry(
                rel_path=str(rel),
                title=title,
                description=description,
                date=date,
                sort_key=sort_key,
            )
            groups.setdefault(subdir, []).append(entry)

    # Sort each group: newest first (via negated date key), then A-Z by title
    for entries in groups.values():
        entries.sort(key=lambda e: e.sort_key)

    return groups


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _pretty_subdir(name: str) -> str:
    """Turn a subdir slug like 'free-tiers' into 'Free Tiers'."""
    return name.replace("-", " ").title()


def generate_index(dir_name: str, subtitle: str, groups: dict[str | None, list[FileEntry]]) -> str:
    """Produce the full text for an INDEX.md."""
    lines: list[str] = []
    header = f"{_pretty_subdir(dir_name)} Index"
    lines.append(f"# {header}")
    lines.append("")
    lines.append(AUTO_GENERATED_NOTICE)
    lines.append("")
    lines.append(subtitle)
    lines.append("")
    lines.append("## Contents")
    lines.append("")

    # Determine if there are subdirectories
    subdirs = sorted(k for k in groups if k is not None)
    root_entries = groups.get(None, [])

    # Root-level files first
    for entry in root_entries:
        lines.append(_format_entry(entry))

    # Then each subdirectory
    for sd in subdirs:
        lines.append(f"### {_pretty_subdir(sd)}")
        lines.append("")
        for entry in groups[sd]:
            lines.append(_format_entry(entry))
        lines.append("")

    # Ensure file ends with exactly one newline
    text = "\n".join(lines).rstrip() + "\n"
    return text


def _format_entry(entry: FileEntry) -> str:
    """Format a single index entry as a markdown list item."""
    date_part = f" ({entry.date})" if entry.date else ""
    desc_part = f" \u2014 {entry.description}" if entry.description else ""
    return f"- [{entry.title}]({entry.rel_path}){date_part}{desc_part}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate INDEX.md files for Gaia Minds content directories."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: exit with code 1 if any INDEX.md is out of date.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated indexes to stdout without writing files.",
    )
    args = parser.parse_args()

    stale: list[str] = []

    for dir_name, subtitle in CONTENT_DIRS.items():
        content_dir = REPO_ROOT / dir_name
        if not content_dir.is_dir():
            print(f"[skip] {dir_name}/ does not exist", file=sys.stderr)
            continue

        groups = scan_directory(content_dir)
        new_content = generate_index(dir_name, subtitle, groups)
        index_path = content_dir / "INDEX.md"

        if args.dry_run:
            sep = "=" * 72
            print(f"\n{sep}")
            print(f"  {index_path.relative_to(REPO_ROOT)}")
            print(sep)
            print(new_content)
            continue

        existing = ""
        if index_path.exists():
            existing = index_path.read_text(encoding="utf-8", errors="replace")

        if existing == new_content:
            print(f"[ok]      {dir_name}/INDEX.md is up to date")
        else:
            if args.check:
                print(f"[stale]   {dir_name}/INDEX.md needs regeneration", file=sys.stderr)
                stale.append(dir_name)
            else:
                index_path.write_text(new_content, encoding="utf-8")
                print(f"[updated] {dir_name}/INDEX.md")

    if args.check and stale:
        print(
            f"\nError: {len(stale)} INDEX.md file(s) are out of date. "
            "Run 'python3 tools/generate-indexes.py' to regenerate.",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
